# The name of this app. Must be unique within a project.
name: nextjs

type: 'nodejs:14'

dependencies:
  nodejs:
    yarn: "1.22.17"
    pm2: "5.2.0"

build:
  flavor: none

variables:
  env:
    NODE_OPTIONS: --max-old-space-size=1536
    GENERATED_VARS: 'deploy/platformsh.environment'

size: L

resources:
  base_memory: 1024
  memory_ratio: 1024

hooks:
  build: |
    # Build dependencies.
    set -e
    #   a. For the main app.
    yarn --frozen-lockfile
    #   b. For our verification test.
    #cd platformsh-scripts/test/next-drupal-debug
    #yarn --frozen-lockfile
  post_deploy: |
    # Verify the connection to the backend can be made with those variables.
    . $GENERATED_VARS
    # cd platformsh-scripts/test/next-drupal-debug && yarn debug
    # Build the frontend.
    cd $PLATFORM_APP_DIR && yarn build

web:
  commands:
    start: |
      # Maybe since we're foregoing the first deploy, yarn start is good enough.
      if [ -f "$GENERATED_VARS" ]; then
          # Source environment variables, build the frontend, and start the server.
          . $GENERATED_VARS
          yarn build
          yarn start
          # APP=$(cat package.json | jq -r '.name')
          # pm2 start npm --no-daemon --watch --name $APP -- preview -- -p $PORT
      else
          # On the first deploy, display next steps page.
          node first_deploy.js
      fi


disk: 512

mounts:
  /.cache:
    source: local
    source_path: 'cache'
  /.next:
    source: local
    source_path: 'next'
  /.pm2:
    source: local
    source_path: 'pm2'
  deploy:
    source: service
    service: files
    source_path: deploy
